import { useQuery } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { buttonClasses } from '@/components/ui/Button'
import { PageHeader } from '@/components/ui/Card'
import { Kpi, KpiStrip, Panel } from '@/components/ui/Panel'
import { SearchInput } from '@/components/ui/SearchInput'
import { Avatar, Code } from '@/components/ui/bits'
import { Async, Skeleton, Stagger, StaggerItem } from '@/components/ui/states'
import { api } from '@/lib/api'
import { money } from '@/lib/constants'
import { useDebounced } from '@/lib/useDebounced'

function monthLabel(m: string) {
  try {
    return new Date(m + '-01T00:00:00').toLocaleDateString('en-GB', { month: 'short', year: 'numeric' })
  } catch {
    return m
  }
}

export function DuesPage() {
  const [q, setQ] = useState('')
  const qDebounced = useDebounced(q)

  const summary = useQuery({ queryKey: ['dues', 'summary'], queryFn: () => api.dues.summary() })
  const list = useQuery({ queryKey: ['dues', 'byStudent', qDebounced], queryFn: () => api.dues.byStudent(qDebounced ? { q: qDebounced } : {}) })

  const rows = list.data ?? []
  const kpis = useMemo(() => summary.data, [summary.data])

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Dues"
        subtitle="Everything still owed, by student — the fees generated by billing cycles that haven’t been fully paid. Collect against them from Payments."
      />

      {summary.isPending || !kpis ? (
        <Skeleton rows={1} />
      ) : (
        <KpiStrip cols={3}>
          <Kpi label="Total outstanding" value={money(kpis.totalDue)} />
          <Kpi label="Students owing" value={kpis.students} foot={kpis.students === 1 ? 'student' : 'students'} />
          <Kpi label="Fees unpaid" value={kpis.records} foot={kpis.records === 1 ? 'record' : 'records'} />
        </KpiStrip>
      )}

      <SearchInput value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search student, ID or subject" wrapClassName="w-full" />

      <Panel title="Outstanding by student" count={list.isPending ? undefined : rows.length}>
        <Async
          query={list}
          isEmpty={(d) => d.length === 0}
          empty={{ icon: 'check', title: 'Nothing outstanding', sub: 'Every generated fee has been paid. New dues appear here when a billing cycle is generated.' }}
        >
          {(students) => (
            <Stagger className="divide-y divide-separator">
              {students.map((s) => (
                <StaggerItem key={s.student_id}>
                  <div className="flex items-start gap-3 px-[18px] py-3">
                    <Avatar name={s.student} />
                    <div className="flex-1 min-w-0">
                      <p className="text-[16.5px] font-[590] tracking-[-0.01em]">
                        {s.student} · <b className="font-[650] text-red">{money(s.total)}</b>
                      </p>
                      <p className="text-[13.5px] text-secondary mt-0.5 flex items-center gap-1.5 flex-wrap">
                        <Code>{s.student_code}</Code>
                        {s.klass && <span>· {s.klass}</span>}
                      </p>
                      <p className="text-[13.5px] text-secondary mt-0.5 tnum">
                        {s.items.map((i) => `${monthLabel(i.month)} ${i.subject} ${money(i.outstanding)}`).join(' · ')}
                      </p>
                    </div>
                    <Link to={`/admin/payments?student=${s.student_id}`} className={buttonClasses('tinted', 'xs')}>
                      Collect
                    </Link>
                  </div>
                </StaggerItem>
              ))}
            </Stagger>
          )}
        </Async>
      </Panel>
    </div>
  )
}
